name: appsagainsthumanity
description: A CaH application for both iOS and Android

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # System Packages
  intl: ^0.16.0
  logging: ^0.11.3+2
  shared_preferences: ^0.5.6
  package_info: ^0.4.0+14
  device_info: ^0.4.1+5
  path_provider: ^1.6.5
  path: ^1.6.4

  # Architecture and Tools
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  rxdart: ^0.23.1
  dartx: ^0.3.0
  kt_dart: ^0.7.0+1
  equatable: ^1.1.1

  # FlutterFire
  firebase_core: 0.4.4
  firebase_auth: 0.15.3
  firebase_analytics: ^5.0.11
  firebase_storage: ^3.1.3
  cloud_firestore: ^0.13.4+1
  google_sign_in: ^4.4.1

  # UI
  material_design_icons_flutter: ^3.4.5045

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.7
  bloc_test: ^3.0.0


builders:
  json_config_builder: 0.0.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/
