name: appsagainsthumanity
description: A CaH application for both iOS and Android

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # System Packages
  intl: ^0.16.0
  logging: ^0.11.3+2
  shared_preferences: ^0.5.6
  package_info: ^0.4.0+14
  device_info: ^0.4.1+5
  path_provider: ^1.6.5
  path: ^1.6.4
  uuid: ^2.0.4
  share: ^0.6.4
  json_annotation: ^3.0.0

  # Architecture and Tools
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  rxdart: ^0.23.1
  #dartx: ^0.3.0
  kt_dart: ^0.7.0+1
  equatable: ^1.1.1

  # FlutterFire
  firebase_core: 0.4.4
  firebase_auth: 0.15.3
  firebase_analytics: ^5.0.11
  firebase_storage: ^3.1.3
  firebase_messaging: ^6.0.13
  firebase_dynamic_links: ^0.5.0+11
  cloud_firestore: ^0.13.4+1
  cloud_functions: ^0.4.2+3
  google_sign_in: ^4.4.1
  apple_sign_in: ^0.1.0

  # UI
  material_design_icons_flutter: ^3.4.5045
  timeago: ^2.0.26
  webview_flutter: ^0.3.20+2
  flutter_signin_button: ^1.0.0
  image_picker: ^0.6.5+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.7
  bloc_test: ^3.0.0
  build_runner: ^1.0.0
  json_serializable: ^3.2.0

builders:
  json_config_builder: 0.0.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/
