name: appsagainsthumanity
description: A CaH application for both iOS and Android

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+10

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # System Packages
  intl: ^0.17.0
  logging: ^0.11.3+2
  shared_preferences: ^2.0.4
  package_info: ^0.4.0+14
  device_info: ^0.4.1+5
  path_provider: ^2.0.1
  path: ^1.6.4
  uuid: ^3.0.1
  share: ^0.6.4
  json_annotation: ^3.0.0
  wiredash: 0.6.2
  email_validator: ^2.0.1
  dartx: ^0.7.0

  # Architecture and Tools
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  rxdart: ^0.23.1
  kt_dart: ^0.7.0+1
  equatable: ^1.1.1

  # FlutterFire
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  firebase_analytics: ^7.1.1
  firebase_storage: ^8.0.0
  firebase_messaging: ^9.0.0
  firebase_dynamic_links: ^0.8.0
  cloud_firestore: ^1.0.1
  cloud_functions: ^1.0.0
  google_sign_in: ^5.0.0
  sign_in_with_apple: ^3.0.0

  # UI
  material_design_icons_flutter: ^4.0.5855
  timeago: ^2.0.29
  webview_flutter: ^2.0.2
  easy_web_view: ^1.4.0-nullsafety
  flutter_signin_button: ^1.1.0
  image_picker: ^0.7.3
  image_picker_for_web: ^2.0.0
  google_fonts: ^2.0.0
  clipboard: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^3.0.0
  build_runner: ^1.0.0
  json_serializable: ^3.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/
